### ISSUE TITLE
download LUCY  

### ISSUE THREAD

**Issue by taohr2006** [Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io#1]
Hi, When i want to download the Model-64bit of LUCY. it just have 134b and i can not unzip it. i do not know why. 
Besides User Manual - Version 2014a, can you give some advices in the detailed process of LUCY model installation.
Thank you very much and look forward to your reply.

**Comment by sunt05** [comment]
Thanks for reporting this issue.
Now the download link has been fixed and you should be able to install it following the instructions in  LUCY manual.

**Comment by sunt05** [comment]
fixed #1

**Comment by taohr2006** [comment]
Hi, thank you for your reply, the model can download, but Translation tool between Matlab binary format and ASCII raster: mat2ascGUI.exe  still can not download.

**Comment by sunt05** [comment]
@taohr2006 thanks for reporting the issue.
Link to `mat2ascGUI.exe` has been fixed.

**Comment by taohr2006** [comment]
i try to download mat2ascGUI.exe, but is just 406kb and can not unzip

**Comment by sunt05** [comment]
@taohr2006 sorry we've been undergoing some issues with the file host service. Can you try again please? Hopefully it is resolved now.

**Comment by taohr2006** [comment]
no, it still don't work.

**Comment by sunt05** [comment]
Try to clear your browser's cache. Or, try it with another browser.

**Comment by taohr2006** [comment]
Model-64bit can download, but mat2ascGUI.exe is still just 407kb

**Comment by sunt05** [comment]
`mat2ascGUI.exe ` is small: it is 417kb.

**Comment by taohr2006** [comment]
this mat2ascGUI.exe just can install in version 7.16 of MCR

**Comment by taohr2006** [comment]
By the way,  if i want to install LUCY model in Linux, how can get the model?

**Comment by sunt05** [comment]
please read the manual for MCR installation.
Unfortunately, LUCY is not available on Linux as a standalone version.

**Comment by taohr2006** [comment]
ok, thank you.

**Comment by taohr2006** [comment]
After finished the installation of LUCY, i try to run the model following the User Manual. After i finished the step 1 to 4 and Press EXECUTE, the window is always in the situation of "processing Datasets". But in the output folder, there is no data or other results. I am confused and why is it?

**Comment by taohr2006** [comment]
Please give me some advices. Thank you very much.

**Comment by biglimp** [comment]
Please do the following:
1. Open a command prompt window (cmd.exe) as administrator. This is done by right-click on cmd.exe and choosing 'Run as Administrator'.
2. Locate the folder where the LUCY program are located.
3. Run the program, make your settings and press EXECUTE.
4. Report back any output from the command prompt.
5. ALso check if a log text file was created in the LUCY folder. If so, attach it to your respons.

**Comment by sunt05** [comment]
please continue the discussion in #2, which is more related to the question.
