### ISSUE TITLE
LUCY model: hanging on "processing Datasets"

### ISSUE THREAD

**Issue by taohr2006** [Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io#2]
After finished the  installation of LUCY,   i try to run the model following the User Manual. After i finished the step 1 to 4 and Press EXECUTE, the window is always in the situation of "processing Datasets". But in the output folder, there is  no data or other results.  I am confused and why is it?

**Comment by taohr2006** [comment]
Please give me some advices. Thank you.

**Comment by suegrimmond** [comment]
Sounds like you are not running software compatible for your computer

**Comment by sunt05** [comment]
@biglimp has provided the following suggestions and I move them from #1:

> Please do the following:
> 1. Open a command prompt window (cmd.exe) as administrator. This is done by right-click on cmd.exe and choosing 'Run as Administrator'.
> 2. Locate the folder where the LUCY program are located.
> 3. Run the program, make your settings and press EXECUTE.
> 4. Report back any output from the command prompt.
> 5. ALso check if a log text file was created in the LUCY folder. If so, attach it to your respons.

**Comment by taohr2006** [comment]
**This is output from the command prompt.  there are many errors and no log text file was created.**   **why is this?**

Error using hgload>localCheckRecursion (line 129)
File C:\Users\Administrator\AppData\Local\Temp\Administrator\mcrCache8.2\LUCY_s0\LUCY_startup\DataSummary.fig recursively loaded itself.

Error in hgload (line 42)



Error in openfig (line 72)



Error in gui_mainfcn>local_openfig (line 286)



Error in gui_mainfcn (line 159)



Error in DataSummary (line 40)



Error in LUCY_datasummary_v2 (line 106)



Error in LUCY_GUI>pushbutton_Run_Callback (line 369)



Error in gui_mainfcn (line 96)

**Comment by taohr2006** [comment]
Did the LUCY model need to be installed under the Administrator mode??

**Comment by taohr2006** [comment]
**Can LUCY model run in window 10?**

**Comment by biglimp** [comment]
No, the software could have been installed by a regular user. 
I think it can be execulted under W10 but I have not tested.

**Comment by biglimp** [comment]
When is your error displayed? When you start the software or later?
I suspect it might be a W10, MCR issue as I cannot reproduce your error on my W7 computer.

**Comment by taohr2006** [comment]
Thank you for your reply. The problem has been resolved. The reason is due to my operating system.

**Comment by taohr2006** [comment]
### **I find i can just get one day result. if i want to get ten days or more, how should i do?**

**Comment by biglimp** [comment]
'Set number of days sequential to model' higher than 1 to model more than on day.

**Comment by taohr2006** [comment]
I am sorry that i don't notice it. Thank you for your help.
