### ISSUE TITLE
how can i make  daily temperature data using mat2ascGUI.exe tool

### ISSUE THREAD

**Issue by taohr2006** [Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io#6]

**Comment by biglimp** [comment]
Could you please specify your issue. mat2asc cannot generate daily temperature but you can convert a GIS daily temperature grid into the correct LUCY format (which must have the same spatial resolution and extent as the other grids used, e.g. population)

**Comment by taohr2006** [comment]
Thanks for your reply. I want to know how can I get daily average temperature data. Can I use wrf out data to do a daily average？ or others methods to make daily tenperature.   Thank you！祝好，恒锐！-------- 原始邮件 --------主题：Re: [Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io] how can i make  daily temperature data using mat2ascGUI.exe tool (#6)发件人：biglimp 收件人："Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io" 抄送：taohr2006 ,Author Could you please specify your issue. mat2asc cannot generate daily temperature but you can convert a GIS daily temperature grid into the correct LUCY format (which must have the same spatial resolution and extent as the other grids used, e.g. population)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io","title":"Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@biglimp in #6: Could you please specify your issue. mat2asc cannot generate daily temperature but you can convert a GIS daily temperature grid into the correct LUCY format (which must have the same spatial resolution and extent as the other grids used, e.g. population)"}],"action":{"name":"View Issue","url":"https://github.com/Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io/issues/6#issuecomment-445766712"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io/issues/6#issuecomment-445766712",
"url": "https://github.com/Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io/issues/6#issuecomment-445766712",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io] how can i make  daily temperature data using mat2ascGUI.exe tool (#6)",
"sections": [
{
"text": "",
"activityTitle": "**biglimp**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@biglimp",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io\",\n\"issueId\": 6,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io\",\n\"issueId\": 6\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Urban-Meteorology-Reading/Urban-Meteorology-Reading.github.io/issues/6#issuecomment-445766712"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 418751244\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by biglimp** [comment]
Yes, you can use any daily dataset as long as it is re-gridded to the scale and extent of the other datasets in LUCY. Please look at the manual for more info. I will close this now as this is not an issue per se.
